
import { FutureCategory } from '../types';

export const FUTURE_IMPROVEMENTS: FutureCategory[] = [
  {
    category: "User Experience (UX) & Design",
    color: "blue",
    iconKey: "Eye",
    items: [
      { title: "High Contrast Mode", desc: "Toggleable themes for users with visual impairments.", iconKey: "Palette" },
      { title: "Keyboard Navigation", desc: "Full tab support for all interactive protocol simulations.", iconKey: "Keyboard" },
      { title: "Screen Reader Optimization", desc: "ARIA labels and detailed descriptions for graphics.", iconKey: "Smartphone" },
      { title: "Adaptive Theme System", desc: "Sync with OS light/dark/dim preferences automatically.", iconKey: "Moon" },
      { title: "Color Blindness Themes", desc: "Protanopia and Deuteranopia accessible color palettes.", iconKey: "Eye" },
      { title: "Custom Accent Picker", desc: "Allow users to choose their preferred UI highlight color.", iconKey: "Palette" },
      { title: "Layout Density Control", desc: "Toggle between Compact and Comfortable viewing modes.", iconKey: "Maximize" },
      { title: "Font Size Controls", desc: "Global typography scaling for better readability.", iconKey: "Type" },
      { title: "Zen Reading Mode", desc: "Distraction-free interface for long-form glossary reading.", iconKey: "BookOpen" },
      { title: "Sticky TOC (Mobile)", desc: "Bottom-sheet table of contents for small screens.", iconKey: "List" },
      { title: "Global Progress Bar", desc: "Visual reading progress indicator at the top of the viewport.", iconKey: "BarChart2" },
      { title: "Interactive Onboarding", desc: "Guided tour for new users explaining dashboard features.", iconKey: "HelpCircle" },
      { title: "Breadcrumb Navigation", desc: "Hierarchical path links for deep glossary pages.", iconKey: "GitMerge" },
      { title: "4K Layout Support", desc: "Optimized grid spacing for ultrawide monitors.", iconKey: "Maximize" },
      { title: "Haptic Feedback", desc: "Vibration feedback on mobile interaction triggers.", iconKey: "Smartphone" },
      { title: "Glassmorphism Slider", desc: "User control over UI transparency and blur effects.", iconKey: "Settings" },
      { title: "Floating Action Button", desc: "Quick access to Search and Glossary from anywhere.", iconKey: "MousePointer" },
      { title: "Contextual Hover Cards", desc: "Rich previews when hovering over technical terms.", iconKey: "Maximize" },
      { title: "Skeleton Loading", desc: "Polished loading states for smoother perceived performance.", iconKey: "Layout" },
      { title: "Back-to-Top Button", desc: "Quick return interaction for long scrolling pages.", iconKey: "ArrowUp" },
      { title: "Section Collapsing", desc: "Ability to fold module sections to save screen space.", iconKey: "Minimize" },
      { title: "Dynamic Cursor Effects", desc: "Subtle visual feedback following mouse movement.", iconKey: "MousePointer" },
      { title: "Mega Menu", desc: "Expanded navigation menu for direct glossary access.", iconKey: "Menu" },
    ],
  },
  {
    category: "Content Depth & Resources",
    color: "emerald",
    iconKey: "BookOpen",
    items: [
      { title: "Expanded Glossary", desc: "Expanded glossary with direct links to related concepts.", iconKey: "Search" },
      { title: "Downloadable Cheatsheets", desc: "PDF summaries of RoCEv2 headers and Congestion Control.", iconKey: "Download" },
      { title: "Real-World Case Studies", desc: "Architectural breakdowns of production-scale AI cluster deployments.", iconKey: "Globe" },
      { title: "Topology Designer", desc: "Drag-and-drop sandbox to build Spine-Leaf networks.", iconKey: "Grid" },
      { title: "Packet Header Visualizer", desc: "Bit-level explorer for Ethernet/IP/UDP/IB headers.", iconKey: "Code" },
      { title: "Latency Budget Calc", desc: "Estimator for serialization, propagation, and queue delay.", iconKey: "Activity" },
      { title: "Power Estimator", desc: "Calculator for cluster power usage (Optics + Switches).", iconKey: "Zap" },
      { title: "Cabling Guide", desc: "Comparison of DAC, AOC, LPO, and CPO technologies.", iconKey: "Network" },
      { title: "ROI Calculator", desc: "Cost benefit analysis tool for Ethernet vs InfiniBand.", iconKey: "BarChart2" },
      { title: "Decision Check", desc: "Short prompts for validating terminology and failure-mode recognition.", iconKey: "CheckSquare" },
      { title: "Architecture Trees", desc: "Decision flowcharts for choosing network topologies.", iconKey: "GitMerge" },
      { title: "History of HPC", desc: "Timeline of evolution from Beowulf clusters to AI Superpods.", iconKey: "Clock" },
      { title: "Vendor Config Gen", desc: "Snippet generator for Arista EOS and SONiC.", iconKey: "Terminal" },
      { title: "Meta LLaMA 3 Study", desc: "Deep dive into the 24k GPU cluster architecture.", iconKey: "Server" },
      { title: "Tesla Dojo Study", desc: "Analysis of custom transport and D1 chip networking.", iconKey: "Cpu" },
      { title: "OpenAI GPT-4 Fabric", desc: "Speculative breakdown of the Azure InfiniBand backend.", iconKey: "Cloud" },
      { title: "AI Expert Bot", desc: "LLM-powered chat interface for technical Q&A.", iconKey: "MessageSquare" },
      { title: "Community Forum", desc: "Discussion board for network engineers.", iconKey: "Users" },
      { title: "Whitepaper Library", desc: "Curated collection of IEEE and ACM research papers.", iconKey: "FileText" },
      { title: "Video Explainers", desc: "Animated video series for complex protocol concepts.", iconKey: "Video" },
      { title: "Protocol State Machines", desc: "Visual flowcharts of TCP and RoCE state transitions.", iconKey: "Activity" },
      { title: "Optical Physics", desc: "Deep dive into PAM4, SerDes, and Signal Integrity.", iconKey: "Zap" },
      { title: "Telemetry Lab", desc: "Sandboxed environment to analyze INT data packets.", iconKey: "Microscope" },
      { title: "Vendor Comparisons", desc: "Side-by-side spec sheets for Nvidia, Arista, and Cisco.", iconKey: "GitCompare" },
      { title: "Podcast Integration", desc: "Embedded player for 'Packet Pushers' and AI network podcasts.", iconKey: "Mic" },
      { title: "Reference Drilldown", desc: "Short prompts for validating terminology and failure-mode recognition.", iconKey: "BookOpen" },
      { title: "Lab Exercises", desc: "Step-by-step GNS3/EVE-NG topology files for practice.", iconKey: "Terminal" },
    ],
  },
  {
    category: "Technical Performance",
    color: "purple",
    iconKey: "Terminal",
    items: [
      { title: "Offline Reference (PWA)", desc: "Access reference modules without an internet connection.", iconKey: "Smartphone" },
      { title: "Global Search", desc: "Cmd+K instant search for protocols and specs.", iconKey: "Search" },
      { title: "Reduced Motion", desc: "Respect user OS settings to disable animations.", iconKey: "Eye" },
      { title: "WebGL Visualization", desc: "3D accelerated graphics for topology rendering.", iconKey: "Box" },
      { title: "Server-Side Rendering", desc: "Migration to Next.js for SEO and faster First Paint.", iconKey: "Server" },
      { title: "Edge Caching", desc: "Global CDN distribution for low-latency asset delivery.", iconKey: "Globe" },
      { title: "Vector Search", desc: "Semantic search engine for natural language queries.", iconKey: "Search" },
      { title: "Internationalization", desc: "Multi-language support (i18n) for global access.", iconKey: "Globe" },
      { title: "Print Stylesheets", desc: "Optimized CSS for printing glossary and guides.", iconKey: "Printer" },
      { title: "User Progress Sync", desc: "Cloud persistence of reference review state.", iconKey: "Cloud" },
      { title: "Local Note Taking", desc: "Browser-based markdown notes for each module.", iconKey: "Edit2" },
      { title: "Bookmark System", desc: "Save specific sections or terms for later review.", iconKey: "Bookmark" },
      { title: "Database Integration", desc: "Supabase backend for dynamic content management.", iconKey: "Database" },
      { title: "CI/CD Pipeline", desc: "Visualizer for the deployment process of this app.", iconKey: "GitMerge" },
      { title: "Automated A11y", desc: "Integration of Axe for continuous accessibility testing.", iconKey: "Check" },
      { title: "Image Optimization", desc: "Auto-conversion to AVIF/WebP formats.", iconKey: "Image" },
      { title: "Code Splitting", desc: "Dynamic imports to reduce initial bundle size.", iconKey: "Code" },
      { title: "Service Worker", desc: "Advanced caching strategies for offline resilience.", iconKey: "WifiOff" },
      { title: "WebAssembly Sim", desc: "High-performance physics engine for packet simulation.", iconKey: "Cpu" },
      { title: "Analytics Dashboard", desc: "Privacy-focused usage metrics and heatmaps.", iconKey: "BarChart2" },
      { title: "Error Logging", desc: "Sentry integration for production crash tracking.", iconKey: "AlertTriangle" },
      { title: "JSON Data Export", desc: "Allow users to export their notes and progress.", iconKey: "Download" },
      { title: "Real-time Collab", desc: "Multi-user cursors for shared topology editing.", iconKey: "Users" },
      { title: "GraphQL API", desc: "Expose reference content via a public API endpoint.", iconKey: "Code" },
      { title: "Lighthouse CI", desc: "Automated performance regression testing.", iconKey: "Zap" },
      { title: "Dark Mode Optimization", desc: "OLED-black theme for mobile battery savings.", iconKey: "Moon" },
      { title: "Keyboard Shortcuts", desc: "Vim-style navigation bindings for power users.", iconKey: "Keyboard" },
    ],
  },
];
