
export const GLOSSARY: Record<string, string> = {
  // --- Infrastructure & Topology ---
  "Radix": "The number of ports on a switch. High radix switches (e.g., 64-port 800G) allow for flatter network topologies with fewer hops, reducing latency.",
  "Leaf-Spine": "A two-tier network topology where every leaf switch connects to every spine switch, minimizing latency and ensuring consistent bandwidth.",
  "Clos": "A multistage circuit-switching network which represents a theoretical ideal for non-blocking networks, the foundation of modern AI fabrics.",
  "Fat-Tree": "A network topology where bandwidth increases closer to the root, maintaining 1:1 subscription ratio at all levels to prevent bottlenecks.",
  "Dragonfly": "A direct-connect topology used in HPC that groups routers into groups, minimizing the diameter of the network but often requiring adaptive routing.",
  "Torus": "A ring-based topology where nodes are connected to their nearest neighbors in multiple dimensions (2D, 3D), common in traditional supercomputing.",
  "Superpod": "A cluster unit in NVIDIA architectures (e.g., 32 DGX nodes) connected via NVLink/Infiniband, representing a building block for larger AI data centers.",
  "Rail-Optimized": "A cabling topology where GPU #N from every server connects to the same leaf switch (Rail N). When GPU #1 on Server A communicates with GPU #1 on Server B, the traffic traverses a single leaf switch — a single-hop path. This minimizes latency for rail-local collective operations and reduces spine load compared to a traditional fat-tree where all GPU NICs attach to a single TOR leaf.",
  "Non-Blocking": "A network property where any input port can be connected to any free output port without internal contention.",
  "Bisection Bandwidth": "The bandwidth available between two equal-sized partitions of a network; a key measure of network capacity for all-to-all communication.",
  "Oversubscription": "The ratio of total downstream (host-facing) bandwidth to upstream (fabric-facing) bandwidth. AI training backend fabrics require 1:1 — any oversubscription creates bottlenecks during synchronized collective operations. The frontend fabric (dataset ingest, management, storage) can tolerate 4:1–8:1 oversubscription. Exception: in checkpoint-heavy environments, simultaneous checkpoint flushes can saturate storage uplinks, requiring a tighter frontend ratio.",
  "East-West Traffic": "Network traffic flows between servers within a data center (e.g., GPU-to-GPU training), as opposed to North-South traffic (Client-to-Server).",
  "North-South Traffic": "Network traffic entering or leaving the data center (e.g., User requests to Web Server).",
  "Scale-Up": "The domain of GPU interconnects within a single node or rack — NVLink, NVSwitch, or high-density Ethernet for intra-chassis communication. Scale-up bandwidth is measured in terabits per second across the backplane or switch fabric within the scale-up island. The boundary where scale-up ends and scale-out (external network fabric) begins is a critical design decision: a larger scale-up island means fewer but larger traffic events crossing the external fabric.",
  "Scale-Out": "The domain of GPU-to-GPU communication across the external Ethernet fabric — leaf-spine topology connecting many servers. Scale-out handles all-reduce and other collectives that span beyond a single scale-up island. Non-blocking, low-latency, 1:1 subscription fabric is required because synchronized elephant flows from collectives expose every weak assumption in queueing, load balancing, and path symmetry.",
  "BGP": "Border Gateway Protocol. The routing protocol used to distribute loopbacks, point-to-point reachability, and EVPN overlay state in modern datacenter fabrics. In AI fabric validation, BGP session health is the first baseline test: all BGP sessions must be established and stable before congestion or collective tests are meaningful. Uses eBGP between leaves and spines (different ASNs per device) for simple, explicit adjacency boundaries.",
  "MTU": "Maximum Transmission Unit. The largest frame size allowed on a network interface. AI fabrics require jumbo frames — typically 9214 bytes — to absorb VXLAN encapsulation overhead (50–54 bytes) and ensure RDMA payloads are not fragmented. MTU mismatch is a common silent failure: EOS sets the outer DF bit on VXLAN packets, so undersized MTU causes drops with no error messages. End-to-end MTU verification is a mandatory baseline test in AI fabric POC validation.",

  // --- Data Movement & Transport ---
  "RoCE": "RDMA over Converged Ethernet. A network protocol that allows remote direct memory access over an Ethernet network, requiring a lossless fabric.",
  "RoCEv2": "Version 2 of RoCE. Encapsulates IB packets in UDP/IP (destination port 4791), making it fully routable across leaf-spine fabrics — unlike RoCEv1, which was confined to a single L2 broadcast domain. The UDP source port provides entropy for ECMP hash distribution across equal-cost paths. Depends on a lossless queue design (PFC + ECN) to function correctly.",
  "InfiniBand": "A high-speed, low-latency networking standard historically used in HPC, utilizing credit-based flow control to ensure lossless transmission.",
  "UEC": "Ultra Ethernet Consortium. An organization defining new Ethernet standards (UET) specifically optimized for AI and HPC to handle packet loss gracefully.",
  "UET": "Ultra Ethernet Transport. A next-generation transport protocol from UEC featuring packet spraying, flexible ordering, and selective recovery.",
  "TCP/IP": "Transmission Control Protocol/Internet Protocol. The backbone of the internet. Reliable but often too high-latency and CPU-intensive for internal AI fabric communication.",
  "NVMe-oF": "NVMe over Fabrics. Extending the NVMe storage protocol over networks (TCP, RoCE, FC) to access remote SSDs with local-like performance.",
  "GPUDirect": "NVIDIA technology enabling direct communication between GPUs, or between GPUs and network adapters (RDMA), bypassing the host CPU.",
  "NVLink": "A high-bandwidth, energy-efficient proprietary interconnect developed by NVIDIA for peer-to-peer GPU communication within a node or rack.",
  "RDMA": "Remote Direct Memory Access. A networking model that allows a host to directly read or write data in remote host memory without involving the CPU or OS kernel of either machine — bypassing the operating system entirely. The data plane is handled by the NIC, freeing CPU resources for the AI workload. Requires a disciplined network environment: more sensitive to loss and congestion than TCP. The foundation of GPU-to-GPU data movement in AI training clusters.",
  "DLB": "Dynamic Load Balancing. An Arista EOS feature that improves on static hash-based ECMP by reacting to observed flow behavior. DLB evaluates the queue depth and recent data-transmitted load of each ECMP member port and steers new traffic away from congested links. Supported on Strata-family ASICs only (not Jericho). Configured at the leaf layer to reduce hot-spot formation during bursty AI collective operations.",
  "CLB": "Cluster Load Balancing. An Arista EOS feature that identifies RoCEv2-based collective communication flows at the spine and allocates them to use all available leaf uplinks evenly. Unlike DLB (which reacts to queue depth), CLB is collective-aware — designed specifically for GPU cluster all-reduce traffic patterns. Configured on spine switches only; can coexist with DLB on leaves. Requires a multi-agent coordination model.",

  // --- Congestion & Flow Control ---
  "PFC": "Priority Flow Control. A link-level backpressure mechanism that pauses selected no-drop traffic classes on a congested interface to prevent packet loss. Scoped to a priority class, not an individual flow; effective only on the local link, not end-to-end. Designed as a safety backstop — brief and local. Sustained or spreading PFC pause indicates the congestion-control loop (ECN/DCQCN) is too slow or mis-tuned.",
  "ECN": "Explicit Congestion Notification. A switch-side mechanism that marks packets on a congested queue before loss occurs, so RoCEv2 endpoints can invoke end-to-end rate reduction via DCQCN without waiting for drops. Operates as a pre-loss signal feeding the congestion-control loop. Design goal: ECN appears early enough that DCQCN can reduce offered load, keeping PFC as a short-timescale backstop only.",
  "DCQCN": "Data Center Quantized Congestion Notification. A rate-based, end-to-end congestion control scheme for RoCEv2 fabrics with three roles: the Congestion Point (CP) — the switch that marks ECN bits when queue occupancy exceeds threshold; the Notification Point (NP) — the receiving NIC that generates a Congestion Notification Packet (CNP); and the Reaction Point (RP) — the sending NIC that receives the CNP and rate-limits the flow. ECN provides flow-level rate control; PFC provides the instantaneous no-drop backstop.",
  "Incast": "A traffic pattern where many senders transmit to a single receiver simultaneously, overwhelming its ingress buffer. In AI fabrics, synchronized collective operations (all-reduce, all-gather) create recurring, coordinated incast events — not random bursts. When congestion-control loops are too slow to respond, incast pressure can propagate upstream via PFC and turn a localized buffer event into a fabric-wide stall.",
  "Microburst": "A sudden, intense spike in traffic lasting microseconds. Too fast for SNMP polling to detect, but large enough to overflow shallow buffers.",
  "Head-of-Line Blocking": "A performance issue where a line of packets is held up by the first packet, preventing subsequent packets (even those going to other destinations) from moving.",
  "Tail Latency": "The latency experienced by the slowest percentage (e.g., 99th percentile) of requests. In AI, the tail latency defines the step time for the entire cluster.",
  "Goodput": "The number of useful information bits delivered by the network per unit of time, excluding retransmissions and protocol overhead.",
  "Packet Spraying": "A load balancing technique that distributes individual packets from a single flow across all available equal-cost paths simultaneously. Unlike ECMP (which hashes per-flow), packet spraying eliminates hash collision entirely by bypassing flow affinity. Requires the receiving NIC to tolerate out-of-order delivery — making it native to UET transports. Pairs with packet trimming to enable fast selective retransmit without waiting for retransmission timeouts.",
  "Entropy": "Randomness introduced into packet headers (e.g., source UDP port) to help hash-based load balancers (ECMP) distribute traffic evenly.",
  "Jitter": "The variation in packet delay (latency). High jitter can disrupt synchronization in AI training collectives.",
  "ECMP": "Equal-Cost Multi-Path. The default load-distribution mechanism in AI fabrics — hashes on packet header fields and spreads traffic across equal-cost paths. Static hash-based ECMP is a starting point, not the end state: synchronized RDMA elephant flows from AI collectives frequently collide on the same links while adjacent paths stay underused. AI fabrics typically improve on ECMP with Dynamic Load Balancing (DLB) at the leaf or Cluster Load Balancing (CLB) at the spine.",
  "CNP": "Congestion Notification Packet. A control message generated by the receiving GPU NIC in a DCQCN congestion-control loop. When the receiving NIC observes ECN-marked packets arriving on a RoCEv2 flow, it generates a CNP and sends it back to the originating NIC. The sender's NIC receives the CNP and rate-limits the identified flow. CNP generation is a mandatory validation step when verifying RoCEv2 congestion control is functioning end-to-end.",
  "Elephant Flow": "A large, long-lived network flow that consumes significant bandwidth over time. In AI fabrics, synchronized all-reduce operations create coordinated elephant flows from every GPU simultaneously. Static ECMP hash-based load balancing may distribute flow count acceptably while a few colliding elephant flows dominate congestion behavior. Elephant flow awareness is the primary motivation for DLB and CLB over static ECMP.",
  "All-to-All": "A collective communication operation where every node sends a distinct chunk of data to every other node, resulting in each node holding a complete rearrangement of the distributed dataset. Used in Mixture-of-Experts (MoE) models during expert routing. Creates the most demanding traffic pattern of any collective — pure many-to-many entropy — stressing fabric load balancing and creating the highest incast risk at any given receiver.",
  "TSN": "Time Spent in Networking. The portion of distributed training time consumed by collective communication and network operations, as opposed to compute. The key metric for connecting network behavior to job completion time: a fabric that increases TSN by 10% extends total training time proportionally. More operationally useful than interface utilization alone because it measures network impact on actual workload progress.",
  "PFC Watchdog": "A protection mechanism that stops a PFC pause storm from propagating through the fabric when a host NIC behaves pathologically. If a NIC continuously floods pause frames, the watchdog can stop reacting to received pause, drop affected traffic, or take other containment actions to protect the broader fabric. Mandatory to test during POC validation: simulate a 'mad NIC' flooding pause and verify containment behavior is correct.",
  "LANZ": "Latency Analyzer. An Arista EOS telemetry feature that monitors egress queue depth in real time and generates alerts when queue occupancy exceeds a configured threshold. LANZ provides sub-second visibility into microbursts that SNMP polling cannot detect. A prerequisite for AI fabric observability: confirms that congestion events are visible to operators before tuning thresholds or diagnosing collective performance issues. Enabled by default on Jericho platforms; must be explicitly enabled on Strata platforms.",

  // --- Platform & Silicon ---
  "ASIC": "Application-Specific Integrated Circuit. The silicon chip inside a switch (e.g., Broadcom Tomahawk, Jericho) that performs packet forwarding logic.",
  "VOQ": "Virtual Output Queuing. A buffering architecture where packets are queued at the ingress based on their egress destination, eliminating Head-of-Line blocking.",
  "Deep Buffers": "Large memory pools (GBs) on switches/routers designed to absorb traffic bursts without dropping packets, crucial for WAN and lossless fabrics.",
  "SerDes": "Serializer/Deserializer. Functional blocks that convert parallel data to serial data for transmission over high-speed links.",
  "PAM4": "Pulse Amplitude Modulation 4-level. A modulation technique used in modern high-speed Ethernet (400G/800G) to encode two bits per symbol.",
  "LPO": "Linear Pluggable Optics. Optical modules that remove the DSP (Digital Signal Processor) to reduce power consumption and latency by up to 50%.",
  "CPO": "Co-Packaged Optics. Optics integrated directly onto the switch package substrate to maximize density and minimize electrical drive distance.",
  "SmartNIC": "A Network Interface Card with programmable compute resources (ARM cores, FPGA) to offload networking tasks (OVS, Encryption, RDMA) from the host CPU.",
  "DPU": "Data Processing Unit. An evolved SmartNIC specialized for infrastructure offloading, isolating the tenant OS from the infrastructure control plane.",
  "PCIe": "Peripheral Component Interconnect Express. A high-speed serial computer expansion bus standard for connecting GPUs, NICS, and SSDs to the host CPU.",
  "Switch Fabric": "The internal mesh of connections within a switch or router that directs traffic from input ports to output ports.",
  "Retimer": "A mixed-signal device used to extend the reach of high-speed signals by recovering the clock and regenerating the data.",
  "OSFP": "Octal Small Form-factor Pluggable. A large pluggable transceiver format used for 400G and 800G optical modules, designed for better thermal management.",
  "QSFP-DD": "Quad Small Form-factor Pluggable Double Density. A high-density transceiver module format backwards compatible with QSFP.",

  // --- Workload Types ---
  "All-Reduce": "A collective communication operation where all participating nodes contribute data (Reduce) and receive the combined result (Broadcast). The dominant pattern in distributed AI training — it creates large, long-lived elephant flows that repeat in tight synchronization across thousands of GPUs. Implemented in ring, tree, and hierarchical forms, each stressing the fabric with different traffic patterns. Network tail latency during All-Reduce directly extends the training step time for the entire cluster.",
  "All-Gather": "A collective operation where every node gathers data from every other node, resulting in every node having a complete copy of the dataset.",
  "Scatter-Gather": "A pattern where a primary node distributes chunks of data to workers (Scatter) and collects results back (Gather).",
  "Barrier Synchronization": "A checkpoint in distributed computing where all tasks must wait until every member of the group has reached the point before any can proceed.",
  "Straggler": "A slow task, node, or link that delays the completion of a synchronized workload, causing the entire cluster to idle.",
  "Checkpointing": "The process of saving the current state of an AI model to persistent storage (NVMe/S3) so training can resume after a failure.",
  "Gradient Descent": "An optimization algorithm used to minimize the loss function in AI training by iteratively adjusting model parameters.",
  "Model Parallelism": "Splitting a single large AI model across multiple GPUs because it doesn't fit in the memory of a single device.",
  "Data Parallelism": "Replicating the entire model across multiple GPUs, where each GPU processes a different batch of training data.",
  "JCT": "Job Completion Time. The total time taken to train an AI model. In distributed training, JCT is directly impacted by network tail latency.",
  "Inference": "The phase where a trained AI model is used to generate predictions or content based on new input data.",
  "Training": "The computational process of teaching an AI model by feeding it massive datasets to adjust its internal weights.",
  "Parameter": "A configuration variable that is internal to the model and whose value can be estimated from data. LLMs have billions or trillions of parameters.",
  "Epoch": "One complete pass of the training algorithm through the entire training dataset.",
  "Batch Size": "The number of training examples utilized in one iteration.",
  "Floating Point Operations": "FLOPs. A measure of computer performance, critical for quantifying AI training compute requirements.",
  "GPU": "Graphics Processing Unit. A specialized electronic circuit designed to manipulate and alter memory to accelerate the creation of images, now the standard for AI compute.",
  "TPU": "Tensor Processing Unit. An AI accelerator application-specific integrated circuit (ASIC) developed by Google specifically for neural network machine learning.",
};

/** Maps each glossary term to its domain category for filter-chip grouping. */
export const GLOSSARY_TERM_DOMAINS: Record<string, string> = {
  // Infrastructure & Topology
  "Radix": "Infrastructure & Topology",
  "Leaf-Spine": "Infrastructure & Topology",
  "Clos": "Infrastructure & Topology",
  "Fat-Tree": "Infrastructure & Topology",
  "Dragonfly": "Infrastructure & Topology",
  "Torus": "Infrastructure & Topology",
  "Superpod": "Infrastructure & Topology",
  "Rail-Optimized": "Infrastructure & Topology",
  "Non-Blocking": "Infrastructure & Topology",
  "Bisection Bandwidth": "Infrastructure & Topology",
  "Oversubscription": "Infrastructure & Topology",
  "East-West Traffic": "Infrastructure & Topology",
  "North-South Traffic": "Infrastructure & Topology",
  "Scale-Up": "Infrastructure & Topology",
  "Scale-Out": "Infrastructure & Topology",
  "BGP": "Infrastructure & Topology",
  "MTU": "Infrastructure & Topology",
  // Data Movement & Transport
  "RoCE": "Data Movement & Transport",
  "RoCEv2": "Data Movement & Transport",
  "InfiniBand": "Data Movement & Transport",
  "UEC": "Data Movement & Transport",
  "UET": "Data Movement & Transport",
  "TCP/IP": "Data Movement & Transport",
  "NVMe-oF": "Data Movement & Transport",
  "GPUDirect": "Data Movement & Transport",
  "NVLink": "Data Movement & Transport",
  "RDMA": "Data Movement & Transport",
  "DLB": "Data Movement & Transport",
  "CLB": "Data Movement & Transport",
  // Congestion & Flow Control
  "PFC": "Congestion & Flow Control",
  "ECN": "Congestion & Flow Control",
  "DCQCN": "Congestion & Flow Control",
  "Incast": "Congestion & Flow Control",
  "Microburst": "Congestion & Flow Control",
  "Head-of-Line Blocking": "Congestion & Flow Control",
  "Tail Latency": "Congestion & Flow Control",
  "Goodput": "Congestion & Flow Control",
  "Packet Spraying": "Congestion & Flow Control",
  "Entropy": "Congestion & Flow Control",
  "Jitter": "Congestion & Flow Control",
  "ECMP": "Congestion & Flow Control",
  "CNP": "Congestion & Flow Control",
  "Elephant Flow": "Congestion & Flow Control",
  "All-to-All": "Congestion & Flow Control",
  "TSN": "Congestion & Flow Control",
  "PFC Watchdog": "Congestion & Flow Control",
  "LANZ": "Congestion & Flow Control",
  // Platform & Silicon
  "ASIC": "Platform & Silicon",
  "VOQ": "Platform & Silicon",
  "Deep Buffers": "Platform & Silicon",
  "SerDes": "Platform & Silicon",
  "PAM4": "Platform & Silicon",
  "LPO": "Platform & Silicon",
  "CPO": "Platform & Silicon",
  "SmartNIC": "Platform & Silicon",
  "DPU": "Platform & Silicon",
  "PCIe": "Platform & Silicon",
  "Switch Fabric": "Platform & Silicon",
  "Retimer": "Platform & Silicon",
  "OSFP": "Platform & Silicon",
  "QSFP-DD": "Platform & Silicon",
  // Workload Types
  "All-Reduce": "Workload Types",
  "All-Gather": "Workload Types",
  "Scatter-Gather": "Workload Types",
  "Barrier Synchronization": "Workload Types",
  "Straggler": "Workload Types",
  "Checkpointing": "Workload Types",
  "Gradient Descent": "Workload Types",
  "Model Parallelism": "Workload Types",
  "Data Parallelism": "Workload Types",
  "JCT": "Workload Types",
  "Inference": "Workload Types",
  "Training": "Workload Types",
  "Parameter": "Workload Types",
  "Epoch": "Workload Types",
  "Batch Size": "Workload Types",
  "Floating Point Operations": "Workload Types",
  "GPU": "Workload Types",
  "TPU": "Workload Types",
};
